### ISSUE TITLE
[Transition] : Symfony and dynamism

### ISSUE THREAD

**Issue by SOLUPRED3** [lucastrap/S5-SAE-TOAC-grp2#82]
### Transition

Finishing the transition from static html/css/js to a dynamic approach with the framework symfony to create a more user-friendly administrative interface, to change the contents of the website more easily.

### Sub-tasks

- [ ] #52 
- [ ] #70 
- [ ] #71 
- [ ] #78 
- [ ] Transition et dynamisation de la page de courses
- [ ] Transition et dynamisation de la page de consultation d'une course
- [ ] Transition et dynamisation de la page des épreuves
- [ ] Transition et dynamisation de la page des résultats
- [ ] Transition et dynamisation de la page de newsletter
- [ ] Transition et dynamisation de la page de consultation d'une news
